import pandas, numpy
from app import models, db
import datetime
import calendar
import re
import sys

def initialize_db():
    u = models.User(email='hall2cm@yahoo.com')
    db.session.add(u)
    b = models.Balance(account='Checking', amount='50000.00', user=u)
    db.session.add(b)
    db.session.commit()
    return

def add_category():
    c = models.Category(name='Auto & Transport')
    db.session.add(c)
    c = models.Category(name='Bills & Utilities')
    db.session.add(c)
    c = models.Category(name='Business Services')
    db.session.add(c)
    c = models.Category(name='Education')
    db.session.add(c)
    c = models.Category(name='Entertainment')
    db.session.add(c)
    c = models.Category(name='Fees & Charges')
    db.session.add(c)
    c = models.Category(name='Financial')
    db.session.add(c)
    c = models.Category(name='Food & Dining')
    db.session.add(c)
    c = models.Category(name='Gifts & Donations')
    db.session.add(c)
    c = models.Category(name='Health & Fitness')
    db.session.add(c)
    c = models.Category(name='Home')
    db.session.add(c)
    c = models.Category(name='Income')
    db.session.add(c)
    c = models.Category(name='Kids')
    db.session.add(c)
    c = models.Category(name='Misc Expenses')
    db.session.add(c)
    c = models.Category(name='Personal Care')
    db.session.add(c)
    c = models.Category(name='Pets')
    db.session.add(c)
    c = models.Category(name='Shopping')
    db.session.add(c)
    c = models.Category(name='Taxes')
    db.session.add(c)
    c = models.Category(name='Transfer')
    db.session.add(c)
    c = models.Category(name='Travel')
    db.session.add(c)
    c = models.Category(name='Uncategorized')
    db.session.add(c)
    db.session.commit()

def test_test():
    c = models.Category.query.filter_by(name='Bills & Utilities').first()
    print(c)

def add_sub_category():
    c = models.Category.query.filter_by(name='Auto & Transport').first()
    s = models.SubCategory(name='Auto Insurance', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Auto Payment', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Gas & Fuel', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='License/Taxes', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Parking', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Public Transportation', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Service & Parts', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Bills & Utilities').first()
    s = models.SubCategory(name='Cable & Internet', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Electricity', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Phone', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Internet', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Mobile Phone', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Television', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Utilities', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Water Bill', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Business Services').first()
    s = models.SubCategory(name='Advertising', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Legal', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Office Supplies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Printing', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Shopping', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Education').first()
    s = models.SubCategory(name='Books & Supplies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Student Loans', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Tuition', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Entertainment').first()
    s = models.SubCategory(name='Amusement', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Arts', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Movies & DVDs', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Music', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Newspapers & Magazines', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Fees & Charges').first()
    s = models.SubCategory(name='ATM Fee', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Bank Fee', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Finance Charge', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Late Fee', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Service Fee', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Trade Commissions', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Financial').first()
    s = models.SubCategory(name='Financial Advisor', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='General Savings', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Investment', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Food & Dining').first()
    s = models.SubCategory(name='Alcohol & Bars', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Chicken', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Coffee Shops', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Fast Food', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Groceries', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Restaurants', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Gifts & Donations').first()
    s = models.SubCategory(name='Charity', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Church Tithe', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Gift', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Health & Fitness').first()
    s = models.SubCategory(name='Dentist', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Doctor', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Eye Care', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Gym', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Health Insurance', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Life Insurance', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Pharmacy', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Sports', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Home').first()
    s = models.SubCategory(name='Association Dues', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Furnishings', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Improvement', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Insurance', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Pest Control', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Services', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Home Supplies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='House Projects', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Lawn & Garden', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Mortgage & Rent', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Income').first()
    s = models.SubCategory(name='Bonus', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Interest Income', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Paycheck', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Reimbursement', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Rental Income', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Returned Purchase', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Kids').first()
    s = models.SubCategory(name='Allowance', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Baby Supplies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Babysitter & Daycare', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Child Support', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Kids Activities', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Toys', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Misc Expenses').first()
    s = models.SubCategory(name='Fun Money', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Miscellaneous', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Personal Care').first()
    s = models.SubCategory(name='Cosmetics/Hair', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Hair', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Laundry', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Spa & Massage', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Subscriptions', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Toiletries', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Pets').first()
    s = models.SubCategory(name='Pet Food & Supplies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Pet Grooming', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Veterinary', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Shopping').first()
    s = models.SubCategory(name='Books', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Clothing', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Electronics & Software', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Hobbies', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Sporting Goods', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Taxes').first()
    s = models.SubCategory(name='Federal Tax', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Local Tax', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='State Tax', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Property Tax', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Sales Tax', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Transfer').first()
    s = models.SubCategory(name='Credit Card Payment', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Transfer for Cash Spending', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Transfer to Savings', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Travel').first()
    s = models.SubCategory(name='Air Travel', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Hotel', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Rental Car and Taxi', categoryname=c)
    db.session.add(s)
    c = models.Category.query.filter_by(name='Uncategorized').first()
    s = models.SubCategory(name='Cash & ATM', categoryname=c)
    db.session.add(s)
    s = models.SubCategory(name='Check', categoryname=c)
    db.session.add(s)
    db.session.commit()
