"""empty message

Revision ID: 0e4504ffd713
Revises: 33a46caa9c1e
Create Date: 2017-01-25 11:12:47.508619

"""

# revision identifiers, used by Alembic.
revision = '0e4504ffd713'
down_revision = '33a46caa9c1e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('userbudget', sa.Column('is_bucket', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbudget', 'is_bucket')
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
