"""empty message

Revision ID: 2f5aec753bef
Revises: 43c16b2cc4c4
Create Date: 2017-02-07 16:44:31.936765

"""

# revision identifiers, used by Alembic.
revision = '2f5aec753bef'
down_revision = '43c16b2cc4c4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('user', sa.Column('cobrand_password', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('cobrand_user_name', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['cobrand_user_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'cobrand_user_name')
    op.drop_column('user', 'cobrand_password')
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
