"""empty message

Revision ID: 33a46caa9c1e
Revises: 43a102b7546c
Create Date: 2017-01-10 12:47:15.737277

"""

# revision identifiers, used by Alembic.
revision = '33a46caa9c1e'
down_revision = '43a102b7546c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbudget', sa.Column('created_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbudget', 'created_date')
    ### end Alembic commands ###
