"""empty message

Revision ID: 39c34fec2684
Revises: 0e4504ffd713
Create Date: 2017-02-04 16:31:42.099052

"""

# revision identifiers, used by Alembic.
revision = '39c34fec2684'
down_revision = '0e4504ffd713'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CONTAINER', sa.String(length=40), nullable=True),
    sa.Column('accountName', sa.String(length=40), nullable=True),
    sa.Column('accountNumber', sa.String(length=40), nullable=True),
    sa.Column('accountStatus', sa.String(length=40), nullable=True),
    sa.Column('accountType', sa.String(length=40), nullable=True),
    sa.Column('availableBalanceamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('availableCashamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('availableCreditamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('balanceamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('currentBalanceamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('accountid', sa.String(length=40), nullable=True),
    sa.Column('includeInNetWorth', sa.String(length=40), nullable=True),
    sa.Column('isAsset', sa.String(length=40), nullable=True),
    sa.Column('isManual', sa.String(length=40), nullable=True),
    sa.Column('lastRefreshAttempt', sa.DateTime(), nullable=True),
    sa.Column('lastRefreshed', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('nextRefreshScheduled', sa.DateTime(), nullable=True),
    sa.Column('providerAccountId', sa.String(length=40), nullable=True),
    sa.Column('providerId', sa.String(length=40), nullable=True),
    sa.Column('providerName', sa.String(length=40), nullable=True),
    sa.Column('statusCode', sa.String(length=40), nullable=True),
    sa.Column('statusMessage', sa.String(length=40), nullable=True),
    sa.Column('totalCashLimitamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('totalCreditLineamount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('url', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sessions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('useraccounts')
    ### end Alembic commands ###
