"""empty message

Revision ID: 43a102b7546c
Revises: 467d71d75c19
Create Date: 2017-01-10 10:29:13.834849

"""

# revision identifiers, used by Alembic.
revision = '43a102b7546c'
down_revision = '467d71d75c19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minttransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('original_description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('labels', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('usersubcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usersubcategory_id'], ['usersubcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minttransactions')
    ### end Alembic commands ###
