"""empty message

Revision ID: 43c16b2cc4c4
Revises: 04e4d09edca3
Create Date: 2017-02-05 10:41:43.057226

"""

# revision identifiers, used by Alembic.
revision = '43c16b2cc4c4'
down_revision = '04e4d09edca3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('useraccounts', sa.Column('posting_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useraccounts', 'posting_date')
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
