"""empty message

Revision ID: 467d71d75c19
Revises: ba9c523a6f9a
Create Date: 2016-12-18 15:20:28.135659

"""

# revision identifiers, used by Alembic.
revision = '467d71d75c19'
down_revision = 'ba9c523a6f9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aws_sub', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['aws_sub'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'aws_sub')
    ### end Alembic commands ###
